version: '3.3'

services:
  remoteservice:
    build: remote-service/.
    ports:
      - "8080:8080"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
    volumes:
      - './my-infrastructure/logstash/pipeline/:/usr/share/logstash/pipeline/:ro'
    ports:
      - "5044:5044"
    links:
      - remoteservice

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.0
    container_name: filebeat
    depends_on: ['logstash']
    volumes:
      - './my-infrastructure/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './my-infrastructure/logs/application.log:/mnt/log/application.log:ro'
    links:
      - logstash
